# Generated by Django 4.2 on 2023-04-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='users',
            name='lastName',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
