# Generated by Django 4.2 on 2023-04-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0004_alter_users_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Users', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Teacher', 'Teacher')], max_length=7, null=True),
        ),
    ]
