# Generated by Django 4.2 on 2023-04-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0008_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('S', 'Student'), ('T', 'Teacher')], max_length=7),
        ),
    ]
