# Generated by Django 4.2 on 2023-05-02 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0013_remove_student_id_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
