# Generated by Django 4.2 on 2023-05-02 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0015_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=5)),
                ('class_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='class_taught',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='scholaractapp.class'),
            preserve_default=False,
        ),
    ]
