# Generated by Django 4.2 on 2023-05-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0016_class_rename_firstname_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='subject_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
