# Generated by Django 4.1.7 on 2023-05-03 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0016_class_rename_firstname_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='class_taught',
        ),
    ]
