# Generated by Django 4.2 on 2023-05-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0017_class_subject_name_alter_class_class_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
    ]
