# Generated by Django 4.2 on 2023-05-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0018_alter_class_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('S', 'Student'), ('T', 'Teacher')], max_length=7, null=True),
        ),
    ]
