# Generated by Django 4.2 on 2023-05-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0027_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
