# Generated by Django 4.2 on 2023-05-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0029_alter_class_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='class',
            name='teacher',
        ),
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(blank=True, to='scholaractapp.class'),
        ),
    ]
