# Generated by Django 4.2 on 2023-05-06 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0030_remove_class_created_by_remove_class_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='classes',
        ),
        migrations.AddField(
            model_name='class',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scholaractapp.user'),
        ),
    ]
