# Generated by Django 4.2 on 2023-05-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0031_remove_teacher_classes_class_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(blank=True, to='scholaractapp.class'),
        ),
    ]
