# Generated by Django 4.2 on 2023-05-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0034_alter_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='class_files/'),
        ),
    ]
