# Generated by Django 4.2 on 2023-05-07 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0035_class_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='file',
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='class_files/')),
                ('related_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholaractapp.class')),
            ],
            options={
                'verbose_name': 'Course Material',
                'verbose_name_plural': 'Course Materials',
            },
        ),
    ]
