# Generated by Django 4.2 on 2023-05-08 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0036_remove_class_file_coursematerial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scholaractapp.user'),
            preserve_default=False,
        ),
    ]
