# Generated by Django 4.2.1 on 2023-05-21 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0037_coursematerial_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursematerial',
            name='file',
        ),
        migrations.CreateModel(
            name='MaterialFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='class_files/')),
                ('course_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholaractapp.coursematerial')),
            ],
        ),
    ]
