# Generated by Django 4.2.1 on 2023-05-27 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0038_remove_coursematerial_file_materialfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('related_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholaractapp.class')),
            ],
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='task_files/')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholaractapp.task')),
            ],
        ),
    ]
