# Generated by Django 4.2.1 on 2023-06-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0039_task_taskfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date_time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
