# Generated by Django 4.2.1 on 2023-06-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0040_task_due_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
