# Generated by Django 4.2.1 on 2023-06-11 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0042_remove_task_due_date_time_task_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_submission', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholaractapp.student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholaractapp.task')),
            ],
        ),
    ]
