# Generated by Django 4.2.1 on 2023-06-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0043_tasksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submission_files/'),
        ),
    ]
