# Generated by Django 4.2.1 on 2023-07-04 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0044_tasksubmission_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholaractapp.user'),
        ),
    ]
