# Generated by Django 4.2.1 on 2023-07-14 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0047_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='teacher',
        ),
        migrations.AddField(
            model_name='marks',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scholaractapp.class'),
            preserve_default=False,
        ),
    ]
