# Generated by Django 4.2.1 on 2023-07-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0050_alter_marks_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
