# Generated by Django 4.2.1 on 2023-07-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0051_alter_coursematerial_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
