# Generated by Django 4.2.1 on 2023-07-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0052_alter_coursematerial_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
