# Generated by Django 4.2.3 on 2023-07-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0053_tasksubmission_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='credit_hour',
            field=models.IntegerField(default=150),
        ),
    ]
