# Generated by Django 4.2.3 on 2023-08-13 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0054_class_credit_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='resetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, max_length=5, null=True, unique=True)),
                ('expiry_timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholaractapp.user')),
            ],
        ),
    ]
