# Generated by Django 4.2.3 on 2023-08-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0055_resetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
