# Generated by Django 4.2.3 on 2023-08-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholaractapp', '0056_alter_coursematerial_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
